# docker-compose.override.yml  (place alongside docker-compose.yml)

services:
  app:
    # build from your Git repo
    build: .               # uses the Dockerfile in the project dir
    image: assets-snipeit:latest

    # ***  definitive removal of the 80:80 mapping ***
    ports: !reset []       # requires compose plugin >= 2.24

    expose:
      - "80"               # leave internal HTTP for Traefik

    labels:
      traefik.enable: "true"
      traefik.http.routers.snipeit.rule: "Host(`assets.cehq.io`)"
      traefik.http.routers.snipeit.entrypoints: "websecure"
      traefik.http.routers.snipeit.tls.certresolver: "cf"      # use your resolver’s name
      traefik.http.services.snipeit.loadbalancer.server.port: "80"
      traefik.docker.network: "internal"

    networks:
      - default
      - internal

networks:
  internal:
    external: true
